import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import SideBar from "@/components/SideBar";
import { Toaster } from 'react-hot-toast';
const poppins = Poppins({weight : '400', subsets: ["latin"]})

export const metadata: Metadata = {
  title: "School System",
  // description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${poppins.className} h-full bg-gradient-to-r from-[rgba(58,119,237,1)] to-[rgba(0,164,255,1)]` }>
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
        {children}    
      </body>
    </html>
  );
}
