import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import SideBar from "@/components/SideBar";
import { Toaster } from 'react-hot-toast';
import RoleContextProvider from "../../context/RoleContextProvider";
import { cookies } from "next/headers";
import { decrypt } from "../lib/session";
const poppins = Poppins({weight : '400', subsets: ["latin"]})

export const metadata: Metadata = {
  title: "School System",
  // description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = cookies().get('session')?.value
  const user = await decrypt(session)

  return (
    <html lang="en" className="h-full">
      <body className={`${poppins.className} h-full`}>
        <div className="flex ">
          <div className="h-full">
            <SideBar />
          </div>
          <Toaster
            position="top-center"
            reverseOrder={false}
           />
           {!user && (
            <div>You're not authorize in this page</div>
           )}
           {user && (
            <RoleContextProvider value={user.role as string}>
              <div className="w-full overflow-y-auto">
                {children}
              </div>
            </RoleContextProvider>  
           )}
        </div>
        </body>
    </html>
  );
}
