import type { Metadata } from "next";

import { Poppins } from "next/font/google";
const poppins = Poppins({weight : '400', subsets: ["latin"]})

export const metadata: Metadata = {
  title: "School System",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${poppins.className} h-full`}>
        {children}
        </body>
    </html>
  );
}
